### ISSUE TITLE
Notebook 

### ISSUE THREAD

**Issue by aarvndhNG** [JojoYay/animatediff-cli-prompt-travel#1]
Please update the notebook i have lot of errors 😔

**Comment by JojoYay** [comment]
Thanks for checking
Wow thanks for using that...
I was planning to remove it but r u using it with paperspace?

**Comment by aarvndhNG** [comment]
> Thanks for checking Wow thanks for using that... I was planning to remove it but r u using it with paperspace?

No on colab

**Comment by JojoYay** [comment]
ah okay
just updated for colab user

u can update 1st line to specify your folder and run to boot now

2023年12月30日(土) 午後6:25 That Blackwolf ***@***.***>:

**Comment by aarvndhNG** [comment]
Still have some error

**Comment by aarvndhNG** [comment]
Traceback (most recent call last):
  File "/content/animatediff-cli-prompt-travel/src/animatediff/front.py", line 2, in <module>
    from animatediff.execute import execute
ModuleNotFoundError: No module named 'animatediff

**Comment by JojoYay** [comment]
you have to read ReadMe and do installation properly.
![image](https://github.com/JojoYay/animatediff-cli-prompt-travel/assets/43402296/de32fd0b-9305-4dc4-9294-33c1d03bbbc1)
